In [1]:
from utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from training import train, do_ensemble, do_train
from eval_erisk import evaluate
from IPython.display import display, Markdown
from itertools import product
from numpy.random import seed
import tensorflow

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
seed(42)
tensorflow.random.set_seed(42) 
logger("Initialized numpy random and tensorflow random seed at 42")

Initialized numpy random and tensorflow random seed at 42


### With max_size = 10 and new data, sample_weights=10, oversample False, include_new_data=True

In [3]:
train_users, y_train, test_users, y_test, train_samples, X_train, X_test = windowfy(window_size=10, max_size=10, sample_weights_size=10, is_oversample=False, include_new_data=True)


feats_train, feats_test = featurize(calculate_feats=True, include_feats=["first_prons","sentiment","nssi"], 
                       train_users=train_users, test_users=test_users)
batch_size=32

Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%Data size: 967

Finished windowfying
Featurizing calculate_feats=True, normalize=False, discretize=False, discretize_size=10, include_feats=['first_prons', 'sentiment', 'nssi']
Initialized numpy random and tensorflow random seed at 42
Data size: 967, 967
Data size: 841, 841
Calculating first prons
Calculating sentiment
Calculating NSSI words
Calculating first prons
Calculating sentiment
Calculating NSSI words


In [4]:
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=cnn_model and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00044: early stopping
Evaluating
27/27 [==============================] - 1s 8ms/step - loss: 0.8798 - tp: 123.0000 - fp: 130.0000 - tn: 506.0000 - fn: 82.0000 - accuracy: 0.7479 - precision: 0.4862 - recall: 0.6000 - f1_metric: 0.4707
Test Score: 0.8797976970672607
Test Accuracy: 123.0
27/27 [==============================] - 0s 7ms/step
Entered here
              precision    recall  f1-score   support

           0       0.86      0.80      0.83       636
           1       0.49      0.60      0.54       205

    accuracy                           0.75       841
   macro avg       0.67      0.70      0.68       841
weighted avg       0.77      0.75      0.76       841

[[506 130]
 [ 82 123]]
Finished training and evaluation
{'precision': 0.48201438848920863, 'recall': 0.6442307692307693,

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00052: early stopping
Evaluating
27/27 [==============================] - 1s 8ms/step - loss: 0.6317 - tp: 103.0000 - fp: 74.0000 - tn: 562.0000 - fn: 102.0000 - accuracy: 0.7907 - precision: 0.5819 - recall: 0.5024 - f1_metric: 0.4681
Test Score: 0.6316781044006348
Test Accuracy: 103.0
27/27 [==============================] - 0s 7ms/step
Entered here
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       636
           1       0.58      0.50      0.54       205

    accuracy                           0.79       841
   macro avg       0.71      0.69      0.70       841
weighted avg       0.78      0.79      0.79       841

[[562  74]
 [102 103]]
Finished training and evaluation
{'precision': 0.5729166666666666, 'recall': 0.5288461538461539, 'F1': 0.5499999999999999, 'ERDE_5': 0.2693720661394234, 'ERDE_50': 0.13966992494229552, 'median_lat

{'precision': 0.6615384615384615,
 'recall': 0.41346153846153844,
 'F1': 0.5088757396449703,
 'ERDE_5': 0.25839872495461313,
 'ERDE_50': 0.1569952327459495,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.4890396416808622}

In [5]:
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_32 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00012: early stopping
Evaluating
27/27 [==============================] - 7s 170ms/step - loss: 1.7052 - tp: 137.0000 - fp: 517.0000 - tn: 119.0000 - fn: 68.0000 - accuracy: 0.3044 - precision: 0.2095 - recall: 0.6683 - f1_metric: 0.3102
Test Score: 1.7051887512207031
Test Accuracy: 137.0
27/27 [==============================] - 6s 179ms/step
Entered here
              precision    recall  f1-score   support

           0       0.64      0.19      0.29       636
           1       0.21      0.67      0.32       205

    accuracy                           0.30       841
   macro avg       0.42      0.43      0.30       841
weighted avg       0.53      0.30      0.30       841

[[119 517]
 [ 68 137]]
Finished training and evaluation
{'precision': 0.2182890855457227, 'recall': 0.7115384615

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00011: early stopping
Evaluating
27/27 [==============================] - 7s 180ms/step - loss: 4.6295 - tp: 205.0000 - fp: 636.0000 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 0.2438 - precision: 0.2438 - recall: 1.0000 - f1_metric: 0.3753
Test Score: 4.629457950592041
Test Accuracy: 205.0
27/27 [==============================] - 6s 182ms/step
Entered here
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       636
           1       0.24      1.00      0.39       205

    accuracy                           0.24       841
   macro avg       0.12      0.50      0.20       841
weighted avg       0.06      0.24      0.10       841

[[  0 636]
 [  0 205]]
Finished training and evaluation
{'precision': 0.2458628841607565, 'recall': 1.0, 'F1': 0.3946869070208729, 'ERDE_5': 0.43066928425293466, 'ERDE_50': 0.18541432635291089, 'median_latency_t

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00012: early stopping
Evaluating
27/27 [==============================] - 6s 164ms/step - loss: 1.3995 - tp: 203.0000 - fp: 634.0000 - tn: 2.0000 - fn: 2.0000 - accuracy: 0.2438 - precision: 0.2425 - recall: 0.9902 - f1_metric: 0.3732
Test Score: 1.3994919061660767
Test Accuracy: 203.0
27/27 [==============================] - 5s 164ms/step
Entered here
              precision    recall  f1-score   support

           0       0.50      0.00      0.01       636
           1       0.24      0.99      0.39       205

    accuracy                           0.24       841
   macro avg       0.37      0.50      0.20       841
weighted avg       0.44      0.24      0.10       841

[[  2 634]
 [  2 203]]
Finished training and evaluation
{'precision': 0.24644549763033174, 'recall': 1.0, 'F1': 0.3954372623574145, 'ERDE_5': 0.4300954314391372, 'ERDE_50': 0.1848330902201432, 'median_latency_tps': 11.

{'precision': 0.3096085409252669,
 'recall': 0.8365384615384616,
 'F1': 0.45194805194805204,
 'ERDE_5': 0.35811414021881693,
 'ERDE_50': 0.15294893505245097,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.43433100885736753}

In [6]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, model_names=["cnn_model", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable embedding_1/embeddings:0 due to variable shape (14941, 100) and value shape (20883, 100) are incompatible

In [7]:
# with different batch_size and all that

In [8]:
model_name="lstm_model_16"
patience=10

In [9]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00012: early stopping
Evaluating
27/27 [==============================] - 4s 98ms/step - loss: 0.7755 - tp: 178.0000 - fp: 385.0000 - tn: 251.0000 - fn: 27.0000 - accuracy: 0.5101 - precision: 0.3162 - recall: 0.8683 - f1_metric: 0.4387
Test Score: 0.775481641292572
Test Accuracy: 178.0
27/27 [==============================] - 4s 100ms/step
Entered here
              precision    recall  f1-score   support

           0       0.90      0.39      0.55       636
           1       0.32      0.87      0.46       205

    accuracy                           0.51       841
   macro avg       0.61      0.63      0.51       841
weighted avg       0.76      0.51      0.53       841

[[251 385]
 [ 27 178]]
Finished training and evaluation
{'precision': 0.31208053691275167, 'recall': 0.89423076923

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", "lstm_model_16", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

In [ ]:
# this time with batch-size = 16

In [10]:
batch_size=16

In [11]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=16
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00011: early stopping
Evaluating
27/27 [==============================] - 4s 110ms/step - loss: 78.8537 - tp: 205.0000 - fp: 636.0000 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 0.2438 - precision: 0.2438 - recall: 1.0000 - f1_metric: 0.3753
Test Score: 78.8536605834961
Test Accuracy: 205.0
53/53 [==============================] - 5s 75ms/step
Entered here
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       636
           1       0.24      1.00      0.39       205

    accuracy                           0.24       841
   macro avg       0.12      0.50      0.20       841
weighted avg       0.06      0.24      0.10       841

[[  0 636]
 [  0 205]]
Finished training and evaluation
{'precision': 0.2458628841607565, 'recall': 1.0, 'F1'

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00011: early stopping
Evaluating
27/27 [==============================] - 4s 104ms/step - loss: 35.9097 - tp: 205.0000 - fp: 636.0000 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 0.2438 - precision: 0.2438 - recall: 1.0000 - f1_metric: 0.3753
Test Score: 35.90967559814453
Test Accuracy: 205.0
53/53 [==============================] - 5s 83ms/step
Entered here
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       636
           1       0.24      1.00      0.39       205

    accuracy                           0.24       841
   macro avg       0.12      0.50      0.20       841
weighted avg       0.06      0.24      0.10       841

[[  0 636]
 [  0 205]]
Finished training and evaluation
{'precision': 0.2458628841607565, 'recall': 1.0, 'F1': 0.3946869070208729, 'ERDE_5': 0.43066928425293466, 'ERDE_50': 0.18541432635291089, 'median_latency_t

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00013: early stopping
Evaluating
27/27 [==============================] - 4s 103ms/step - loss: 3.4110 - tp: 171.0000 - fp: 561.0000 - tn: 75.0000 - fn: 34.0000 - accuracy: 0.2925 - precision: 0.2336 - recall: 0.8341 - f1_metric: 0.3497
Test Score: 3.410984516143799
Test Accuracy: 171.0
53/53 [==============================] - 5s 83ms/step
Entered here
              precision    recall  f1-score   support

           0       0.69      0.12      0.20       636
           1       0.23      0.83      0.36       205

    accuracy                           0.29       841
   macro avg       0.46      0.48      0.28       841
weighted avg       0.58      0.29      0.24       841

[[ 75 561]
 [ 34 171]]
Finished training and evaluation
{'precision': 0.23529411764705882, 'recall': 0.8461538461538461, 'F1': 0.3682008368200837, 'ERDE_5': 0.4115894023076051, 'ERDE_50': 0.20405859307323015, 'median_l

{'precision': 0.23529411764705882,
 'recall': 0.8461538461538461,
 'F1': 0.3682008368200837,
 'ERDE_5': 0.4115894023076051,
 'ERDE_50': 0.20405859307323015,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.35384828019255543}

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)