In [1]:
from utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from training import train, do_ensemble, do_train
from eval_erisk import evaluate
from IPython.display import display, Markdown
from itertools import product
from numpy.random import seed
import tensorflow

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
seed(42)
tensorflow.random.set_seed(42) 
logger("Initialized numpy random and tensorflow random seed at 42")

Initialized numpy random and tensorflow random seed at 42


### With max_size = 10 and new data, sample_weights=10, oversample False, include_new_data=True

In [3]:
train_users, y_train, test_users, y_test, train_samples, X_train, X_test = windowfy(window_size=10, max_size=10, sample_weights_size=10, is_oversample=False, include_new_data=True)


feats_train, feats_test = featurize(calculate_feats=True, include_feats=["first_prons","nssi"], 
                       train_users=train_users, test_users=test_users)
batch_size=32

Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%Data size: 967

Finished windowfying
Featurizing calculate_feats=True, normalize=False, discretize=False, discretize_size=10, include_feats=['first_prons', 'nssi']
Initialized numpy random and tensorflow random seed at 42
Data size: 967, 967
Data size: 841, 841
Calculating first prons
Calculating NSSI words
Calculating first prons
Calculating NSSI words


In [4]:
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=cnn_model and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00044: early stopping
Evaluating
27/27 [==============================] - 3s 24ms/step - loss: 0.7558 - tp: 114.0000 - fp: 95.0000 - tn: 541.0000 - fn: 91.0000 - accuracy: 0.7788 - precision: 0.5455 - recall: 0.5561 - f1_metric: 0.4844
Test Score: 0.7557809948921204
Test Accuracy: 114.0
27/27 [==============================] - 1s 19ms/step
Entered here
              precision    recall  f1-score   support

           0       0.86      0.85      0.85       636
           1       0.55      0.56      0.55       205

    accuracy                           0.78       841
   macro avg       0.70      0.70      0.70       841
weighted avg       0.78      0.78      0.78       841

[[541  95]
 [ 91 114]]
Finished training and evaluation
{'precision': 0.543859649122807, 'recall': 0.5961538461538461, 

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00036: early stopping
Evaluating
27/27 [==============================] - 4s 20ms/step - loss: 0.7134 - tp: 107.0000 - fp: 123.0000 - tn: 513.0000 - fn: 98.0000 - accuracy: 0.7372 - precision: 0.4652 - recall: 0.5220 - f1_metric: 0.4186
Test Score: 0.71340012550354
Test Accuracy: 107.0
27/27 [==============================] - 1s 19ms/step
Entered here
              precision    recall  f1-score   support

           0       0.84      0.81      0.82       636
           1       0.47      0.52      0.49       205

    accuracy                           0.74       841
   macro avg       0.65      0.66      0.66       841
weighted avg       0.75      0.74      0.74       841

[[513 123]
 [ 98 107]]
Finished training and evaluation
{'precision': 0.46774193548387094, 'recall': 0.5576923076923077, 'F1': 0.5087719298245613, 'ERDE_5': 0.28388543312417286, 'ERDE_50': 0.1471086296799289, 'median_la

{'precision': 0.46774193548387094,
 'recall': 0.5576923076923077,
 'F1': 0.5087719298245613,
 'ERDE_5': 0.28388543312417286,
 'ERDE_50': 0.1471086296799289,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.4889398783920656}

In [5]:
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_32 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00012: early stopping
Evaluating
27/27 [==============================] - 20s 569ms/step - loss: 1.1659 - tp: 143.0000 - fp: 202.0000 - tn: 434.0000 - fn: 62.0000 - accuracy: 0.6861 - precision: 0.4145 - recall: 0.6976 - f1_metric: 0.4600
Test Score: 1.165852665901184
Test Accuracy: 143.0
27/27 [==============================] - 17s 555ms/step
Entered here
              precision    recall  f1-score   support

           0       0.88      0.68      0.77       636
           1       0.41      0.70      0.52       205

    accuracy                           0.69       841
   macro avg       0.64      0.69      0.64       841
weighted avg       0.76      0.69      0.71       841

[[434 202]
 [ 62 143]]
Finished training and evaluation
{'precision': 0.4076086956521739, 'recall': 0.721153846

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [6]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, model_names=["cnn_model", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable dense_2/kernel:0 due to variable shape (71, 32) and value shape (72, 32) are incompatible

In [7]:
# with different batch_size and all that

In [8]:
model_name="lstm_model_16"
patience=10

In [9]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00011: early stopping
Evaluating
27/27 [==============================] - 5s 117ms/step - loss: 25.4262 - tp: 205.0000 - fp: 636.0000 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 0.2438 - precision: 0.2438 - recall: 1.0000 - f1_metric: 0.3753
Test Score: 25.426172256469727
Test Accuracy: 205.0
27/27 [==============================] - 4s 106ms/step
Entered here
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       636
           1       0.24      1.00      0.39       205

    accuracy                           0.24       841
   macro avg       0.12      0.50      0.20       841
weighted avg       0.06      0.24      0.10       841

[[  0 636]
 [  0 205]]
Finished training and evaluation
{'precision': 0.2458628841607565, 'recall': 1.0, '

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00029: early stopping
Evaluating
27/27 [==============================] - 8s 182ms/step - loss: 0.5206 - tp: 124.0000 - fp: 98.0000 - tn: 538.0000 - fn: 81.0000 - accuracy: 0.7872 - precision: 0.5586 - recall: 0.6049 - f1_metric: 0.5194
Test Score: 0.5205910801887512
Test Accuracy: 124.0
27/27 [==============================] - 6s 179ms/step
Entered here
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       636
           1       0.56      0.60      0.58       205

    accuracy                           0.79       841
   macro avg       0.71      0.73      0.72       841
weighted avg       0.79      0.79      0.79       841

[[538  98]
 [ 81 124]]
Finished training and evaluation
{'precision': 0.5149253731343284, 'recall': 0.6634615384615384, 'F1': 0.5798319327731092, 'ERDE_5': 0.28324358875792816, 'ERDE_50': 0.12052266541477345, 'median

{'precision': 0.39473684210526316,
 'recall': 0.7211538461538461,
 'F1': 0.510204081632653,
 'ERDE_5': 0.3122740143869122,
 'ERDE_50': 0.1354000748900402,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.49031620458036135}

In [10]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable embedding_1/embeddings:0 due to variable shape (14941, 100) and value shape (20883, 100) are incompatible

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", "lstm_model_16", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

In [11]:
# this time with batch-size = 16

In [12]:
batch_size=16

In [13]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=16
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00031: early stopping
Evaluating
27/27 [==============================] - 4s 104ms/step - loss: 0.7018 - tp: 193.0000 - fp: 613.0000 - tn: 23.0000 - fn: 12.0000 - accuracy: 0.2568 - precision: 0.2395 - recall: 0.9415 - f1_metric: 0.3639
Test Score: 0.7017557621002197
Test Accuracy: 193.0
53/53 [==============================] - 5s 78ms/step
Entered here
              precision    recall  f1-score   support

           0       0.66      0.04      0.07       636
           1       0.24      0.94      0.38       205

    accuracy                           0.26       841
   macro avg       0.45      0.49      0.23       841
weighted avg       0.56      0.26      0.14       841

[[ 23 613]
 [ 12 193]]
Finished training and evaluation
{'precision': 0.24634146341463414, 'recall': 0.97115384615

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)