In [1]:
from utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from training import train, do_ensemble, do_train
from eval_erisk import evaluate
from IPython.display import display, Markdown
from itertools import product
from numpy.random import seed
import tensorflow

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
seed(42)
tensorflow.random.set_seed(42) 
logger("Initialized numpy random and tensorflow random seed at 42")

Initialized numpy random and tensorflow random seed at 42


### With max_size = 10 and new data, sample_weights=10, oversample False, include_new_data=True

In [3]:
train_users, y_train, test_users, y_test, train_samples, X_train, X_test = windowfy(window_size=10, max_size=10, sample_weights_size=10, is_oversample=False, include_new_data=True)


feats_train, feats_test = featurize(calculate_feats=True, include_feats=["first_prons"], 
                       train_users=train_users, test_users=test_users)
batch_size=32

Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%Data size: 967

Finished windowfying
Featurizing calculate_feats=True, normalize=False, discretize=False, discretize_size=10, include_feats=['first_prons']
Initialized numpy random and tensorflow random seed at 42
Data size: 967, 967
Data size: 841, 841
Calculating first prons
Calculating first prons


In [4]:
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=cnn_model and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00039: early stopping
Evaluating
27/27 [==============================] - 3s 24ms/step - loss: 0.9527 - tp: 135.0000 - fp: 168.0000 - tn: 468.0000 - fn: 70.0000 - accuracy: 0.7170 - precision: 0.4455 - recall: 0.6585 - f1_metric: 0.5072
Test Score: 0.9527215361595154
Test Accuracy: 135.0
27/27 [==============================] - 1s 21ms/step
Entered here
              precision    recall  f1-score   support

           0       0.87      0.74      0.80       636
           1       0.45      0.66      0.53       205

    accuracy                           0.72       841
   macro avg       0.66      0.70      0.66       841
weighted avg       0.77      0.72      0.73       841

[[468 168]
 [ 70 135]]
Finished training and evaluation
{'precision': 0.43478260869565216, 'recall': 0.673076923076923

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00049: early stopping
Evaluating
27/27 [==============================] - 2s 9ms/step - loss: 0.6203 - tp: 105.0000 - fp: 79.0000 - tn: 557.0000 - fn: 100.0000 - accuracy: 0.7872 - precision: 0.5707 - recall: 0.5122 - f1_metric: 0.4568
Test Score: 0.6203367114067078
Test Accuracy: 105.0
27/27 [==============================] - 0s 7ms/step
Entered here
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       636
           1       0.57      0.51      0.54       205

    accuracy                           0.79       841
   macro avg       0.71      0.69      0.70       841
weighted avg       0.78      0.79      0.78       841

[[557  79]
 [100 105]]
Finished training and evaluation
{'precision': 0.5686274509803921, 'recall': 0.5576923076923077, 'F1': 0.5631067961165048, 'ERDE_5': 0.27109823820328244, 'ERDE_50': 0.1343214347590385, 'median_lat

{'precision': 0.5686274509803921,
 'recall': 0.5576923076923077,
 'F1': 0.5631067961165048,
 'ERDE_5': 0.27109823820328244,
 'ERDE_50': 0.1343214347590385,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.541156758608694}

In [5]:
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_32 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00012: early stopping
Evaluating
27/27 [==============================] - 19s 538ms/step - loss: 1.2252 - tp: 143.0000 - fp: 210.0000 - tn: 426.0000 - fn: 62.0000 - accuracy: 0.6766 - precision: 0.4051 - recall: 0.6976 - f1_metric: 0.4503
Test Score: 1.2251935005187988
Test Accuracy: 143.0
27/27 [==============================] - 17s 553ms/step
Entered here
              precision    recall  f1-score   support

           0       0.87      0.67      0.76       636
           1       0.41      0.70      0.51       205

    accuracy                           0.68       841
   macro avg       0.64      0.68      0.64       841
weighted avg       0.76      0.68      0.70       841

[[426 210]
 [ 62 143]]
Finished training and evaluation
{'precision': 0.39893617021276595, 'recall': 0.7211538

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [6]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, model_names=["cnn_model", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable dense_2/kernel:0 due to variable shape (67, 32) and value shape (72, 32) are incompatible

In [7]:
# with different batch_size and all that

In [8]:
model_name="lstm_model_16"
patience=10

In [9]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00011: early stopping
Evaluating
27/27 [==============================] - 4s 99ms/step - loss: 27.4870 - tp: 205.0000 - fp: 636.0000 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 0.2438 - precision: 0.2438 - recall: 1.0000 - f1_metric: 0.3753
Test Score: 27.48702049255371
Test Accuracy: 205.0
27/27 [==============================] - 3s 98ms/step
Entered here
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       636
           1       0.24      1.00      0.39       205

    accuracy                           0.24       841
   macro avg       0.12      0.50      0.20       841
weighted avg       0.06      0.24      0.10       841

[[  0 636]
 [  0 205]]
Finished training and evaluation
{'precision': 0.2458628841607565, 'recall': 1.0, 'F1'

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00017: early stopping
Evaluating
27/27 [==============================] - 8s 181ms/step - loss: 0.6991 - tp: 137.0000 - fp: 159.0000 - tn: 477.0000 - fn: 68.0000 - accuracy: 0.7301 - precision: 0.4628 - recall: 0.6683 - f1_metric: 0.4831
Test Score: 0.6990692615509033
Test Accuracy: 137.0
27/27 [==============================] - 6s 179ms/step
Entered here
              precision    recall  f1-score   support

           0       0.88      0.75      0.81       636
           1       0.46      0.67      0.55       205

    accuracy                           0.73       841
   macro avg       0.67      0.71      0.68       841
weighted avg       0.77      0.73      0.74       841

[[477 159]
 [ 68 137]]
Finished training and evaluation
{'precision': 0.45, 'recall': 0.6923076923076923, 'F1': 0.5454545454545455, 'ERDE_5': 0.29659448347714207, 'ERDE_50': 0.12679889788687132, 'median_latency_tps'

{'precision': 0.3978494623655914,
 'recall': 0.7115384615384616,
 'F1': 0.5103448275862068,
 'ERDE_5': 0.3105324597739385,
 'ERDE_50': 0.13602043268559036,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.49045146422300423}

In [10]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable embedding_1/embeddings:0 due to variable shape (14941, 100) and value shape (20883, 100) are incompatible

In [ ]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", "lstm_model_16", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

In [11]:
# this time with batch-size = 16

In [12]:
batch_size=16

In [13]:
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name=model_name, maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=16
Generating embeddings
Data size: 967
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00031: early stopping
Evaluating
27/27 [==============================] - 5s 112ms/step - loss: 0.7068 - tp: 195.0000 - fp: 620.0000 - tn: 16.0000 - fn: 10.0000 - accuracy: 0.2509 - precision: 0.2393 - recall: 0.9512 - f1_metric: 0.3644
Test Score: 0.706753134727478
Test Accuracy: 195.0
53/53 [==============================] - 5s 81ms/step
Entered here
              precision    recall  f1-score   support

           0       0.62      0.03      0.05       636
           1       0.24      0.95      0.38       205

    accuracy                           0.25       841
   macro avg       0.43      0.49      0.22       841
weighted avg       0.52      0.25      0.13       841

[[ 16 620]
 [ 10 195]]
Finished training and evaluation
{'precision': 0.24455205811138014, 'recall': 0.971153846153

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [14]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=patience, model_names=["cnn_model", model_name], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

OSError: Unable to open file (unable to open file: name = 'models/cnn_model100016True.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)