In [1]:
from utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from training import train, do_ensemble, do_train
from eval_erisk import evaluate
from IPython.display import display, Markdown
from itertools import product
from numpy.random import seed
import tensorflow

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
seed(42)
tensorflow.random.set_seed(42) 
logger("Initialized numpy random and tensorflow random seed at 42")

Initialized numpy random and tensorflow random seed at 42


### With max_size = 10 and new data, sample_weights=10, oversample False, include_new_data=True

In [3]:
train_users, y_train, test_users, y_test, train_samples, X_train, X_test = windowfy(window_size=10, max_size=2, sample_weights_size=2, is_oversample=False, include_new_data=True)

feats_train, feats_test = featurize(calculate_feats=True, include_feats=["first_prons","sentiment","nssi"], 
                       train_users=train_users, test_users=test_users)
batch_size = 2

Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%Data size: 495

Finished windowfying
Featurizing calculate_feats=True, normalize=False, discretize=False, discretize_size=10, include_feats=['first_prons', 'sentiment', 'nssi']
Initialized numpy random and tensorflow random seed at 42
Data size: 495, 495
Data size: 423, 423
Calculating first prons
Calculating sentiment
Calculating NSSI words
Calculating first prons
Calculating sentiment
Calculating NSSI words


In [4]:
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=2, batch_size=batch_size,
         shuffle=True, patience=2, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=cnn_model and maxlen=1000 and batch size=2
Generating embeddings
Data size: 495
Training with callback
Evaluating
14/14 [==============================] - 1s 8ms/step - loss: 2.0954 - tp: 0.0000e+00 - fp: 5.0000 - tn: 314.0000 - fn: 104.0000 - accuracy: 0.7423 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_metric: 0.0000e+00
Test Score: 2.0954325199127197
Test Accuracy: 0.0
212/212 [==============================] - 0s 2ms/step
Entered here
              precision    recall  f1-score   support

           0       0.75      0.98      0.85       319
           1       0.00      0.00      0.00       104

    accuracy                           0.74       423
   macro avg       0.38      0.49      0.43       423
weighted avg       0.57      0.74      0.64       423

[[314   5]
 [104   0]]
Finished training and evaluation
{'precision': 0, 'recall': 0, 'F1': 0, 'ERDE_5': 0.24876906482459524, 'ERDE_50': 0.24876906482459524, 'median_latency_tps': nan, 'median

/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


{'precision': 0,
 'recall': 0,
 'F1': 0,
 'ERDE_5': 0.24876906482459524,
 'ERDE_50': 0.24876906482459524,
 'median_latency_tps': nan,
 'median_penalty_tps': nan,
 'speed': nan,
 'latency_weighted_f1': nan}

In [5]:
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=2, batch_size=batch_size,
         shuffle=True, patience=2, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_32 and maxlen=1000 and batch size=2
Generating embeddings
Data size: 495
Training with callback
Evaluating
14/14 [==============================] - 3s 142ms/step - loss: 10.2276 - tp: 67.0000 - fp: 83.0000 - tn: 236.0000 - fn: 37.0000 - accuracy: 0.7163 - precision: 0.4467 - recall: 0.6442 - f1_metric: 0.5084
Test Score: 10.227619171142578
Test Accuracy: 67.0
212/212 [==============================] - 16s 70ms/step
Entered here
              precision    recall  f1-score   support

           0       0.86      0.74      0.80       319
           1       0.45      0.64      0.53       104

    accuracy                           0.72       423
   macro avg       0.66      0.69      0.66       423
weighted avg       0.76      0.72      0.73       423

[[236  83]
 [ 37  67]]
Finished training and evaluation
{'precision': 0.44666666666666666, 'recall': 0.6442307692307693, 'F1': 0.5275590551181102, 'ERDE_5': 0.29371383837789183, 'ERDE_50': 0.135713

{'precision': 0.44666666666666666,
 'recall': 0.6442307692307693,
 'F1': 0.5275590551181102,
 'ERDE_5': 0.29371383837789183,
 'ERDE_50': 0.13571304819229973,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.5069946770511264}

In [8]:
y_pred = do_train(model_name="lstm_model_16", maxlen=1000, epochs=10, batch_size=batch_size,
         shuffle=True, patience=2, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_16 and maxlen=1000 and batch size=2
Generating embeddings
Data size: 495
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00003: early stopping
Evaluating
14/14 [==============================] - 3s 107ms/step - loss: 39.4549 - tp: 104.0000 - fp: 318.0000 - tn: 1.0000 - fn: 0.0000e+00 - accuracy: 0.2482 - precision: 0.2464 - recall: 1.0000 - f1_metric: 0.3881
Test Score: 39.454925537109375
Test Accuracy: 104.0
212/212 [==============================] - 14s 64ms/step
Entered here
              precision    recall  f1-score   support

           0       1.00      0.00      0.01       319
           1       0.25      1.00      0.40       104

    accuracy                           0.25       423
   macro avg       0.62      0.50      0.20       423
weighted avg       0.81      0.25      0.10       423

[[  1 318]
 [  0 104]]
Finished training and evaluation
{'precision': 0.24644549763033174, 'recall': 1.0, 'F1

{'precision': 0.24644549763033174,
 'recall': 1.0,
 'F1': 0.3954372623574145,
 'ERDE_5': 0.4300880481201669,
 'ERDE_50': 0.1848330902201432,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.38002302335232274}

In [7]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=2, batch_size=batch_size,
         shuffle=True, patience=10, model_names=["cnn_model", "lstm_model_16", "lstm_model_32"], 
                  feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Evaluating ensemble
14/14 [==============================] - 5s 150ms/step - loss: 0.5672 - accuracy: 0.7541
Test Score: 0.5672433972358704
Test Accuracy: 0.7541370987892151
212/212 [==============================] - 15s 65ms/step
Entered here
              precision    recall  f1-score   support

           0       0.75      1.00      0.86       319
           1       0.00      0.00      0.00       104

    accuracy                           0.75       423
   macro avg       0.38      0.50      0.43       423
weighted avg       0.57      0.75      0.65       423

[[319   0]
 [104   0]]
{'precision': 0, 'recall': 0, 'F1': 0, 'ERDE_5': 0.2458628841607565, 'ERDE_50': 0.2458628841607565, 'median_latency_tps': nan, 'median_penalty_tps': nan, 'speed': nan, 'latency_weighted_f1': nan}


/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib64/python3.6/site

{'precision': 0,
 'recall': 0,
 'F1': 0,
 'ERDE_5': 0.2458628841607565,
 'ERDE_50': 0.2458628841607565,
 'median_latency_tps': nan,
 'median_penalty_tps': nan,
 'speed': nan,
 'latency_weighted_f1': nan}