### Saved as an example of how to do experiments with this code

In [1]:
from utils import *
from experiment_utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from tfidf_featurizer import combine_features, tfidf_featurize
from training import train, do_ensemble, do_train
from training_traditional import train_and_evaluate
from eval_erisk import evaluate, ensemble_vote
from IPython.display import display, Markdown
from itertools import product
import tensorflow
import numpy as np

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
# experiment params. this is the part that must be modified for a different experiment

seed_part = np.random.randint(1,101,10).tolist()

first_part = {
    "random_seed": seed_part,
    "include_feats": [["first_prons", "nssi"],["first_prons","sentiment","nssi"]],
    "feat_window_size": [10], #10
    "max_size": [20],
    "sample_weights_size": [20],
    "oversample": [True],
    "include_new_data": [True],
    "tfidf_max_features": [5000],
    "scale": [False],
    "normalize": [True],
    "discretize": [True],
    "discretize_size": [50, 75],
    "dis_strategy": ["quantile"]
}

second_part = {
    "eval_window_size": [1],
    "maxlen": [1000],
    "batch_size": [32],
    "epochs": [100],
    "patience": [10],
    "iterations": [5],
    "shuffle": [True],
}

models = ["svm", "bayes", "cnn_model"]
ensemble_combinations = [["svm", "bayes", "cnn_model"]]
weights = [[1, 1, 1], [2, 1, 1], [1, 2, 1], [2, 2, 1], [1, 1, 2], [3, 3, 1], [5, 5, 1], [1, 5, 1]]
eval_filename = "experiments_20-bothdata-seed.csv"

## Experiments

In [ ]:
firstpart_generator = traverse(first_part)

for i in firstpart_generator:
    try:
        # experiment object defined in experiment_utils.py
        experiment = Experiment(models, ensemble_combinations, eval_filename, random_seed=i["random_seed"])
        
        logger("********** CALCULATING FEATURES FOR {} ***********".format(i))
        display(Markdown("#### Calculating features for {}".format(i)))
                
        experiment.prepare_data(i)

        secondpart_generator = traverse(second_part)

        for j in secondpart_generator:
            params = j.copy()
            params.update(i)
            logger("************ STARTING EXPERIMENT {} ***************".format(params))
            display(Markdown("#### Experiment {}".format(params)))
            try:
                experiment.train_and_evaluate_model(params, weights)
                logger("************ FINISHED EXPERIMENT {} ************* \n".format(params))
            except Exception as e:
                logger("*************************************")
                logger("Error during experiment {}: {}".format(params, e))
                logger("*************************************")
        del secondpart_generator
    except Exception as e:
        logger("*************************************")
        logger("General error during experiment {}: {}".format(i, e))
        logger("*************************************")

Initialized numpy random and tensorflow random seed at 79
********** CALCULATING FEATURES FOR {'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 50, 'dis_strategy': 'quantile'} ***********


#### Calculating features for {'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 50, 'dis_strategy': 'quantile'}

PREPARING DATA FOR PARAMS {'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 50, 'dis_strategy': 'quantile'}
Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%
Oversampling train users
After oversample: positive messages: 2792, negative messages: 3491
Data size: 6283

Finished windowfying
Featurizing calculate_feats=True, normalize=True, discretize=True, discretize_size=50, include_feats=['first_prons', 'nssi']
Data size: 6283, 6283
Data size: 4650, 4650
Calculating first prons
Calculating NSSI words
Calculating first prons
Calculating NSSI words
Normalizing features
Discretizing


/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:188: UserWarning: Feature 4 is constant and will be replaced with 0.
  "replaced with 0." % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.loc

Is the combined the same from tfidf: False
************ STARTING EXPERIMENT {'eval_window_size': 1, 'maxlen': 1000, 'batch_size': 32, 'epochs': 100, 'patience': 10, 'iterations': 5, 'shuffle': True, 'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 50, 'dis_strategy': 'quantile'} ***************


#### Experiment {'eval_window_size': 1, 'maxlen': 1000, 'batch_size': 32, 'epochs': 100, 'patience': 10, 'iterations': 5, 'shuffle': True, 'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 50, 'dis_strategy': 'quantile'}

TRAINING AND EVALUATING TRADITIONAL MODEL svm
Starting training traditional
              precision    recall  f1-score   support

           0       0.88      0.83      0.85      3602
           1       0.51      0.61      0.55      1048

    accuracy                           0.78      4650
   macro avg       0.69      0.72      0.70      4650
weighted avg       0.80      0.78      0.79      4650

[[2981  621]
 [ 410  638]]
Evaluating after getting time 295.090787041
              precision    recall  f1-score   support

           0       0.88      0.83      0.85      3602
           1       0.51      0.61      0.55      1048

    accuracy                           0.78      4650
   macro avg       0.69      0.72      0.70      4650
weighted avg       0.80      0.78      0.79      4650

[[2981  621]
 [ 410  638]]
Evaluated with elapsed time 114.53857639900002
EVALUATING FOR WINDOW SIZES 1, 2 AND 3 MODEL svm
{'precision': 0.38596491228070173, 'recall': 0.8461538461538461, 'F1': 0.530

146/146 [==============================] - 3s 11ms/step - loss: 0.4907 - tp: 456.0000 - fp: 370.0000 - tn: 3232.0000 - fn: 592.0000 - accuracy: 0.7931 - precision: 0.5521 - recall: 0.4351 - f1_metric: 0.2825
Test Score: 0.490740567445755
Test Accuracy: 456.0
146/146 [==============================] - 1s 9ms/step
Entered here
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      3602
           1       0.55      0.44      0.49      1048

    accuracy                           0.79      4650
   macro avg       0.70      0.67      0.68      4650
weighted avg       0.78      0.79      0.78      4650

[[3232  370]
 [ 592  456]]
Finished training and evaluation
{'precision': 0.5174825174825175, 'recall': 0.7115384615384616, 'F1': 0.5991902834008097, 'ERDE_5': 0.2856578493668703, 'ERDE_50': 0.11102727897657819, 'median_latency_tps': 11.0, 'median_penalty_tps': 0.03898023902249159, 'speed': 0.9610197609775084, 'latency_weighted_f1': 0.575833702

{'precision': 0.5847457627118644, 'recall': 0.6634615384615384, 'F1': 0.6216216216216216, 'ERDE_5': 0.2740632530733085, 'ERDE_50': 0.11122288729049135, 'median_latency_tps': 11.0, 'median_penalty_tps': 0.03898023902249159, 'speed': 0.9610197609775084, 'latency_weighted_f1': 0.597390662229262}
Writing results to CSV file
{'precision': 0.6237623762376238, 'recall': 0.6057692307692307, 'F1': 0.6146341463414634, 'ERDE_5': 0.26786441033081426, 'ERDE_50': 0.11901368699316878, 'median_latency_tps': 12.0, 'median_penalty_tps': 0.042873701496841665, 'speed': 0.9571262985031583, 'latency_weighted_f1': 0.5882825054214534}
Writing results to CSV file
{'precision': 0.5975609756097561, 'recall': 0.47115384615384615, 'F1': 0.5268817204301075, 'ERDE_5': 0.26501800613564536, 'ERDE_50': 0.14920443304328185, 'median_latency_tps': 13.0, 'median_penalty_tps': 0.046765862163709926, 'speed': 0.9532341378362901, 'latency_weighted_f1': 0.5022416425158948}
Writing results to CSV file
EVALUATING ENSEMBLE ['svm',

#### Calculating features for {'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 75, 'dis_strategy': 'quantile'}

PREPARING DATA FOR PARAMS {'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 75, 'dis_strategy': 'quantile'}
Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%
Oversampling train users
After oversample: positive messages: 2792, negative messages: 3491
Data size: 6283

Finished windowfying
Featurizing calculate_feats=True, normalize=True, discretize=True, discretize_size=75, include_feats=['first_prons', 'nssi']
Data size: 6283, 6283
Data size: 4650, 4650
Calculating first prons
Calculating NSSI words
Calculating first prons
Calculating NSSI words
Normalizing features
Discretizing


/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 3 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:188: UserWarning: Feature 4 is constant and will be replaced with 0.
  "replaced with 0." % jj)
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/preprocessing/_discretization.py:222: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 5 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/home/ecampillo/.loc

Is the combined the same from tfidf: False
************ STARTING EXPERIMENT {'eval_window_size': 1, 'maxlen': 1000, 'batch_size': 32, 'epochs': 100, 'patience': 10, 'iterations': 5, 'shuffle': True, 'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 75, 'dis_strategy': 'quantile'} ***************


#### Experiment {'eval_window_size': 1, 'maxlen': 1000, 'batch_size': 32, 'epochs': 100, 'patience': 10, 'iterations': 5, 'shuffle': True, 'random_seed': 79, 'include_feats': ['first_prons', 'nssi'], 'feat_window_size': 10, 'max_size': 20, 'sample_weights_size': 20, 'oversample': True, 'include_new_data': True, 'tfidf_max_features': 5000, 'scale': False, 'normalize': True, 'discretize': True, 'discretize_size': 75, 'dis_strategy': 'quantile'}

TRAINING AND EVALUATING TRADITIONAL MODEL svm
Starting training traditional
              precision    recall  f1-score   support

           0       0.88      0.83      0.85      3602
           1       0.51      0.60      0.55      1048

    accuracy                           0.78      4650
   macro avg       0.69      0.72      0.70      4650
weighted avg       0.79      0.78      0.78      4650

[[2986  616]
 [ 418  630]]
Evaluating after getting time 4256.656721278
              precision    recall  f1-score   support

           0       0.88      0.83      0.85      3602
           1       0.51      0.60      0.55      1048

    accuracy                           0.78      4650
   macro avg       0.69      0.72      0.70      4650
weighted avg       0.79      0.78      0.78      4650

[[2986  616]
 [ 418  630]]
Evaluated with elapsed time 133.97185154199997
EVALUATING FOR WINDOW SIZES 1, 2 AND 3 MODEL svm
{'precision': 0.3991031390134529, 'recall': 0.8557692307692307, 'F1': 0.544

146/146 [==============================] - 3s 9ms/step - loss: 0.4869 - tp: 431.0000 - fp: 264.0000 - tn: 3338.0000 - fn: 617.0000 - accuracy: 0.8105 - precision: 0.6201 - recall: 0.4113 - f1_metric: 0.2769
Test Score: 0.4869339168071747
Test Accuracy: 431.0
146/146 [==============================] - 1s 8ms/step
Entered here
              precision    recall  f1-score   support

           0       0.84      0.93      0.88      3602
           1       0.62      0.41      0.49      1048

    accuracy                           0.81      4650
   macro avg       0.73      0.67      0.69      4650
weighted avg       0.79      0.81      0.80      4650

[[3338  264]
 [ 617  431]]
Finished training and evaluation
{'precision': 0.53125, 'recall': 0.6538461538461539, 'F1': 0.5862068965517242, 'ERDE_5': 0.28043428758916694, 'ERDE_50': 0.11998055094479108, 'median_latency_tps': 11.0, 'median_penalty_tps': 0.03898023902249159, 'speed': 0.9610197609775084, 'latency_weighted_f1': 0.5633564116075049}
S