In [1]:
from utils import *
from preprocessing import preprocess
from windowfy import windowfy
from featurizing import featurize
from training import train, do_ensemble, do_train
from eval_erisk import evaluate
from IPython.display import display, Markdown
from itertools import product
from numpy.random import seed
import tensorflow

/usr/local/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [2]:
seed(42)
tensorflow.random.set_seed(42) 
logger("Initialized numpy random and tensorflow random seed at 42")

Initialized numpy random and tensorflow random seed at 42


### With max_size = 10 and new data, sample_weights=10, oversample False, include_new_data=True

In [3]:
train_users, y_train, test_users, y_test, train_samples, X_train, X_test = windowfy(window_size=10, max_size=20, sample_weights_size=20, is_oversample=False, include_new_data=True)

feats_train, feats_test = featurize(calculate_feats=True, include_feats=["first_prons","sentiment","nssi"], 
                       train_users=train_users, test_users=test_users)
batch_size=32

Windowfying training users
[====================] 100%
Windowfying test users
[====================] 100%Data size: 5424

Finished windowfying
Featurizing calculate_feats=True, normalize=False, discretize=False, discretize_size=10, include_feats=['first_prons', 'sentiment', 'nssi']
Initialized numpy random and tensorflow random seed at 42
Data size: 5424, 5424
Data size: 4650, 4650
Calculating first prons
Calculating sentiment
Calculating NSSI words
Calculating first prons
Calculating sentiment
Calculating NSSI words


In [4]:
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="cnn_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=30, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=cnn_model and maxlen=1000 and batch size=32
Generating embeddings
Data size: 5424
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00038: early stopping
Evaluating
146/146 [==============================] - 3s 13ms/step - loss: 0.9795 - tp: 687.0000 - fp: 1008.0000 - tn: 2594.0000 - fn: 361.0000 - accuracy: 0.7056 - precision: 0.4053 - recall: 0.6555 - f1_metric: 0.3586
Test Score: 0.97948157787323
Test Accuracy: 687.0
146/146 [==============================] - 2s 10ms/step
Entered here
              precision    recall  f1-score   support

           0       0.88      0.72      0.79      3602
           1       0.41      0.66      0.50      1048

    accuracy                           0.71      4650
   macro avg       0.64      0.69      0.65      4650
weighted avg       0.77      0.71      0.73      4650

[[2594 1008]
 [ 361  687]]
Finished training and evaluation
{'precision': 0.38425925925925924, 'recall': 0.79807

/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ecampillo/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data size: 5424
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00051: early stopping
Evaluating
146/146 [==============================] - 3s 12ms/step - loss: 0.6319 - tp: 534.0000 - fp: 463.0000 - tn: 3139.0000 - fn: 514.0000 - accuracy: 0.7899 - precision: 0.5356 - recall: 0.5095 - f1_metric: 0.3210
Test Score: 0.6318933963775635
Test Accuracy: 534.0
146/146 [==============================] - 2s 11ms/step
Entered here
              precision    recall  f1-score   support

           0       0.86      0.87      0.87      3602
           1       0.54      0.51      0.52      1048

    accuracy                           0.79      4650
   macro avg       0.70      0.69      0.69      4650
weighted avg       0.79      0.79      0.79      4650

[[3139  463]
 [ 514  534]]
Finished training and evaluation
{'precision': 0.5285714285714286, 'recall': 0.7115384615384616, 'F1': 0.6065573770491803, 'ERDE_5': 0.2838774569434117, 'ERDE_50': 0.10928357057827473

{'precision': 0.5285714285714286,
 'recall': 0.7115384615384616,
 'F1': 0.6065573770491803,
 'ERDE_5': 0.2838774569434117,
 'ERDE_50': 0.10928357057827473,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.5829136255109477}

In [5]:
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)
y_pred = do_train(model_name="lstm_model_32", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, train_sample_weights=train_samples)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

Starting training with cnn_model=lstm_model_32 and maxlen=1000 and batch size=32
Generating embeddings
Data size: 5424
Training with callback
Restoring model weights from the end of the best epoch.
Epoch 00013: early stopping
Evaluating
146/146 [==============================] - 27s 172ms/step - loss: 0.8485 - tp: 578.0000 - fp: 742.0000 - tn: 2860.0000 - fn: 470.0000 - accuracy: 0.7394 - precision: 0.4379 - recall: 0.5515 - f1_metric: 0.3253
Test Score: 0.8484840989112854
Test Accuracy: 578.0
146/146 [==============================] - 26s 174ms/step
Entered here
              precision    recall  f1-score   support

           0       0.86      0.79      0.83      3602
           1       0.44      0.55      0.49      1048

    accuracy                           0.74      4650
   macro avg       0.65      0.67      0.66      4650
weighted avg       0.76      0.74      0.75      4650

[[2860  742]
 [ 470  578]]
Finished training and evaluation
{'precision': 0.42045454545454547, 'recall'

{'precision': 0.2458628841607565,
 'recall': 1.0,
 'F1': 0.3946869070208729,
 'ERDE_5': 0.43066928425293466,
 'ERDE_50': 0.18541432635291089,
 'median_latency_tps': 11.0,
 'median_penalty_tps': 0.03898023902249159,
 'speed': 0.9610197609775084,
 'latency_weighted_f1': 0.37930191704615135}

In [6]:
y_pred = do_train(model_name="ensemble_model", maxlen=1000, epochs=100, batch_size=batch_size,
         shuffle=True, patience=10, model_names=["cnn_model", "lstm_model_32"], feats_train=feats_train, feats_test=feats_test, 
         X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test)
evaluate(1, 10, {"test":"test"}, y_pred=y_pred, test_users=test_users)

ValueError: Cannot assign to variable embedding_1/embeddings:0 due to variable shape (20883, 100) and value shape (14941, 100) are incompatible